// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS30BlyYuslQDhYvlCv24095CYpv4F3sA',
    appId: '1:445773704635:web:8b53473d17dd34a7df689e',
    messagingSenderId: '445773704635',
    projectId: 'sistema-avda',
    authDomain: 'sistema-avda.firebaseapp.com',
    storageBucket: 'sistema-avda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD14xHreGvgyBg2zldNW5uADcUrVe7qIM',
    appId: '1:445773704635:android:e417256e3f6eb545df689e',
    messagingSenderId: '445773704635',
    projectId: 'sistema-avda',
    storageBucket: 'sistema-avda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDBDHi5YuW8kMVxhgVXbKbvvBHc9F74rE',
    appId: '1:445773704635:ios:f98e564196378543df689e',
    messagingSenderId: '445773704635',
    projectId: 'sistema-avda',
    storageBucket: 'sistema-avda.appspot.com',
    iosBundleId: 'com.example.avda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDBDHi5YuW8kMVxhgVXbKbvvBHc9F74rE',
    appId: '1:445773704635:ios:f98e564196378543df689e',
    messagingSenderId: '445773704635',
    projectId: 'sistema-avda',
    storageBucket: 'sistema-avda.appspot.com',
    iosBundleId: 'com.example.avda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS30BlyYuslQDhYvlCv24095CYpv4F3sA',
    appId: '1:445773704635:web:7d853b93cfe883ffdf689e',
    messagingSenderId: '445773704635',
    projectId: 'sistema-avda',
    authDomain: 'sistema-avda.firebaseapp.com',
    storageBucket: 'sistema-avda.appspot.com',
  );
}
